<?php
/**
 * WPGraphQL integration for feedback requests.
 *
 * @package Sagiris\Signalboard
 */

declare( strict_types=1 );

namespace Sagiris\Signalboard\GraphQL;

use Sagiris\Signalboard\Content\RequestPostType;

defined( 'ABSPATH' ) || exit;

/**
 * Extends the WPGraphQL schema for the SignalboardRequest type.
 *
 * The type and its connection are generated by WPGraphQL from the post type's
 * `show_in_graphql` settings; status/board `where` filters come from the
 * taxonomies being exposed. This class layers on the plugin-owned fields that
 * WPGraphQL cannot infer (the cached vote count). All of it runs only on the
 * `graphql_register_types` action, which fires exclusively when WPGraphQL is
 * active, so nothing here loads on sites without it.
 */
final class RequestsGraphQL {

	/**
	 * Register custom fields on the generated request type.
	 *
	 * @return void
	 */
	public function register(): void {
		if ( ! function_exists( 'register_graphql_field' ) ) {
			return;
		}

		register_graphql_field(
			'SignalboardRequest',
			'voteCount',
			array(
				'type'        => 'Int',
				'description' => __( 'Cached upvote count for the request.', 'signalboard' ),
				'resolve'     => static function ( $source ): int {
					// WPGraphQL's Post model exposes the ID as the camelCase `databaseId`.
					$post_id = $source->databaseId ?? ( $source->ID ?? 0 ); // phpcs:ignore WordPress.NamingConventions.ValidVariableName.UsedPropertyNotSnakeCase

					return (int) get_post_meta( (int) $post_id, RequestPostType::META_VOTE_COUNT, true );
				},
			)
		);
	}
}
